FROM seancheung/alpinestack:latest
LABEL maintainer="Sean Cheung <theoxuanx@gmail.com>"

ARG CN_MIRROR=false
RUN if [ "$CN_MIRROR" = true ]; then \
		sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
		&& echo 'registry=https://registry.npm.taobao.org' > /root/.npmrc \
	; fi

RUN set -x \
    && echo "Install Dependencies..." \
	&& apk add --no-cache supervisor phpmyadmin php7-fpm nodejs nodejs-npm nginx \
	&& apk add --no-cache --virtual TMP python make g++ \
	&& npm -g i --unsafe-perm mongo-express redis-commander \
	&& mkdir -p /etc/supervisor/conf.d \
	&& for path in \
		/var/run/nginx \
		/var/log/nginx \
	; do \
	mkdir -p "$path"; \
    chown nginx:nginx "$path"; \
	done \
	&& mkdir -p /var/run/php \
	&& echo "listen=/var/run/php7-fpm.sock" >> /etc/php7/php-fpm.conf \
	&& echo "listen.owner=nginx" >> /etc/php7/php-fpm.conf \
	&& echo "listen.group=nginx" >> /etc/php7/php-fpm.conf \
	&& echo "listen.mode=0660" >> /etc/php7/php-fpm.conf \
	&& rm /etc/nginx/conf.d/default.conf \
	&& apk del TMP

COPY phpmyadmin.php /etc/phpmyadmin/config.inc.php
COPY phpmyadmin.conf /etc/nginx/conf.d/
COPY supervisord.conf /etc/
COPY supervisor /etc/supervisor/conf.d/
COPY supervisor-dev /etc/supervisor/conf.d/

VOLUME ["/etc/supervisor/conf.d", "/etc/nginx/conf.d"]
EXPOSE 8080 8081 8082

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]